### PR TITLE
Created Makefile and Buzzer.rdef. Removed Buzzer.proj and Buzzer.rsrc.

### PR DESCRIPTION
**Pull request by owenca**
Also, added <Entry.h> to buzzwindow.cpp to make it compile.

Fixes issue #1

### CODE REVIEW

**Comment by humdingerb** [comment]
There's a confusion about the name of the app. The window title says "WakeUp" and the project here at github, too.  Maybe keep to "WakeUp" for now and we can decide later if we like to rename it.

**Comment by owenca** [comment]
I used "WakeUp". Did I miss something?

**Comment by humdingerb** [comment]
In the rdef there's: short_info = "Buzzer"
Maybe that got me confused... :)
Not sure if it's a good "short info"... Can it be improved?
Maybe "Play a sound after x minutes" or "Alarm clock".

**Comment by owenca** [comment]
The original Buzzer.rdef decompiled from Buzzer.rsrc didn't have any data for short_info and long_info and had several format errors: https://pastebin.com/FRRA6HQp
I wonder what the value for "resource file_types" is. Anyway, I have changed "Buzzer" to "Alarm clock" in the updated PR.

**Comment by humdingerb** [comment]
Thanks.
> I wonder what the value for "resource file_types" is.

Probably just Paladin misfiring...

**Pull request merged**
